// HMAC-signed tokens for the open / click tracking endpoints.
//
// Wire format: `<payload>.<signature>`
//   payload   = base64url(JSON({ e: sentEmailId, r: recipient, u?: url }))
//   signature = base64url(HMAC-SHA256(payload, secret))
//
// Same secret as unsubscribe tokens (`UNSUBSCRIBE_TOKEN_SECRET`) —
// we don't proliferate secrets for what is effectively the same
// "this URL was generated by us" attestation. Different payload shape
// is enough to keep the two use-cases disjoint.

const encoder = new TextEncoder();

function getSecret(env: CloudflareBindings): string {
  const raw = (env as unknown as { UNSUBSCRIBE_TOKEN_SECRET?: string })
    .UNSUBSCRIBE_TOKEN_SECRET;
  if (!raw) {
    throw new Error(
      "UNSUBSCRIBE_TOKEN_SECRET is not configured. Set it with `wrangler secret put UNSUBSCRIBE_TOKEN_SECRET`.",
    );
  }
  return raw;
}

function bytesToBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++)
    binary += String.fromCharCode(bytes[i]);
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

function base64UrlToBytes(input: string): Uint8Array {
  const padded =
    input.replace(/-/g, "+").replace(/_/g, "/") +
    "=".repeat((4 - (input.length % 4)) % 4);
  const binary = atob(padded);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

async function importKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign", "verify"],
  );
}

export interface TrackingPayload {
  /** sent_emails.id this token was issued for. */
  sentEmailId: string;
  /** Canonical recipient address. */
  recipient: string;
  /** Only present for click-tracking links. */
  url?: string;
}

export async function signTrackingToken(
  env: CloudflareBindings,
  payload: TrackingPayload,
): Promise<string> {
  const secret = getSecret(env);
  const body: Record<string, string> = {
    e: payload.sentEmailId,
    r: payload.recipient.trim().toLowerCase(),
  };
  if (payload.url) body.u = payload.url;
  const encoded = bytesToBase64Url(encoder.encode(JSON.stringify(body)));
  const key = await importKey(secret);
  const sig = await crypto.subtle.sign("HMAC", key, encoder.encode(encoded));
  return `${encoded}.${bytesToBase64Url(new Uint8Array(sig))}`;
}

export async function verifyTrackingToken(
  env: CloudflareBindings,
  token: string,
): Promise<TrackingPayload | null> {
  const dot = token.indexOf(".");
  if (dot <= 0 || dot === token.length - 1) return null;
  const encoded = token.slice(0, dot);
  const signature = token.slice(dot + 1);

  let secret: string;
  try {
    secret = getSecret(env);
  } catch {
    return null;
  }

  try {
    const key = await importKey(secret);
    const ok = await crypto.subtle.verify(
      "HMAC",
      key,
      base64UrlToBytes(signature),
      encoder.encode(encoded),
    );
    if (!ok) return null;
    const json = new TextDecoder().decode(base64UrlToBytes(encoded));
    const parsed = JSON.parse(json) as {
      e?: unknown;
      r?: unknown;
      u?: unknown;
    };
    if (
      typeof parsed.e !== "string" ||
      !parsed.e.length ||
      typeof parsed.r !== "string" ||
      !parsed.r.length
    ) {
      return null;
    }
    return {
      sentEmailId: parsed.e,
      recipient: parsed.r,
      url: typeof parsed.u === "string" ? parsed.u : undefined,
    };
  } catch {
    return null;
  }
}
